apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
    - image: tommy351/kubenvoy
      docker: {}
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - test/kubernetes/*.yml
profiles:
  - name: test
    patches:
      - op: add
        path: /build/artifacts/0/docker/target
        value: base
