version: 2.1

commands:
  go_get:
    steps:
      - restore_cache:
          key: go-pkg
      - run: go get ./...
      - save_cache:
          paths:
            - /go/pkg
          key: go-pkg

jobs:
  lint:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - go_get
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
      - run: ./bin/golangci-lint run
  test_go:
    docker:
      - image: circleci/golang:1.11
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - go_get
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./pkg/... ./internal/... ./cmd/... | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
  test_e2e:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Install Go 1.11.5
          command: circleci-install golang 1.11.5
      - run:
          name: Install minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            chmod +x minikube
            sudo mv minikube /usr/local/bin/minikube
      - run:
          name: Install skaffold
          command: |
            curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
            chmod +x skaffold
            sudo mv skaffold /usr/local/bin/skaffold
      - run:
          name: Install kubectl
          command: |
            curl -o kubectl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/kubectl
      - run:
          name: Start minikube
          command: sudo -E minikube start --vm-driver=none
      - run:
          name: Run skaffold
          command: sudo -E skaffold run -f test/skaffold.yml
      - run:
          name: Run tests
          command: go test -v ./test/e2e/...

workflows:
  version: 2
  test:
    jobs:
      - lint
      - test_go
      - test_e2e
